apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= ### Username is defaulted to 'username', change your username and base64 it.
    mongo-root-password: cGFzc3dvcmQ= ### Password is defaulted to 'password', change your password and base64 it.
